sudo: required

language: go

go:
  - master

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y git

script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
  
after_success:
  - bash <(curl -s https://codecov.io/bash)